In [2]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [4]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [5]:
result2 = np.where(cond, xarr, yarr)
result2

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr = np.random.randn(4, 4)
arr

array([[ 0.59102379,  1.02155792, -1.1780215 , -0.71383731],
       [ 1.21522906,  0.7286174 , -2.17585548,  0.96626748],
       [ 0.06370844,  1.97130876,  1.61653462, -0.98344202],
       [ 0.25792715,  0.66351716, -0.41401951,  0.45331727]])

In [7]:
arr > 0

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [8]:
np.where(arr > 0 , 2, -2)

array([[ 2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [ 2,  2,  2, -2],
       [ 2,  2, -2,  2]])

In [10]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -1.1780215 , -0.71383731],
       [ 2.        ,  2.        , -2.17585548,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.98344202],
       [ 2.        ,  2.        , -0.41401951,  2.        ]])