In [3]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('some_array', arr)

In [5]:
np.load('some_array.npy')


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.savez('array_archive.npz', a=arr, b=arr)

In [11]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez_compressed('array_compressed.npz', a=arr, b=arr)

In [16]:
abc = np.load('array_compressed.npz')
abc['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])