In [2]:
import numpy as np

data = np.random.randn(3, 3)
data

array([[ 1.84496004, -0.99717015,  0.83892859],
       [-0.46954223, -0.04687584, -0.55574529],
       [-1.62609056, -1.67148094, -0.45034065]])

In [3]:
data * 10

array([[ 18.44960039,  -9.97170149,   8.38928589],
       [ -4.69542231,  -0.46875838,  -5.55745289],
       [-16.26090558, -16.71480939,  -4.50340645]])

In [4]:
data + data

array([[ 3.68992008, -1.9943403 ,  1.67785718],
       [-0.93908446, -0.09375168, -1.11149058],
       [-3.25218112, -3.34296188, -0.90068129]])

In [11]:
data01 = [1.6, 3, 5, 8, 5.2]
arr01 = np.array(data01)
arr01
arr01.dtype

dtype('float64')

In [12]:
data02 = [2, 3, 9, 4, 6]
arr02 = np.array(data02)
arr02
arr02.shape

(5,)

In [13]:
datta = list()
datta.append(arr01)

In [14]:
datta

[array([1.6, 3. , 5. , 8. , 5.2])]

In [15]:
datta.append(arr02)

In [16]:
datta

[array([1.6, 3. , 5. , 8. , 5.2]), array([2, 3, 9, 4, 6])]

In [22]:
arr02.ndim #dimensão do array

1

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.10343781e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.08221785e-312, 1.06099790e-312]],

       [[1.23075756e-312, 1.03977794e-312],
        [1.12465777e-312, 9.76118064e-313],
        [1.03977794e-312, 1.90979621e-312]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])